#!/bin/bash
cd /kg/

DGLBACKEND=mxnet python3 train.py --model DistMult --dataset FB15k --batch_size 128 \
        --neg_sample_size 16 --hidden_dim 100 --gamma 500.0 --lr 0.1 --max_step 20000 \
        --batch_size_eval 16 --valid --test -adv --eval_interval 1000 --eval_percent 0.01 \
        --num_proc 0 --save_path /opt/ml/output/ --save_emb /opt/ml/model/DistMult_FB15k_emb --data_path /opt/ml/input/data/
